/* ------------------PARTS------------------

MAIN

STUDENT
TEACHER
ADMIN

*** System.out.println("Welcome to EduQuiz! Please select your role below:");
    System.out.println("(1) Student");
    System.out.println("(2) Teacher");
    System.out.println("(3) Admin");
    System.out.print("Enter the number for your role: ");
 


ADMIN INFO :
NAME : admin
PASS : 1234

FOR STUDENT : 
LOGIN
SIGNUP
PASSWORD
**INFO STUDENT
AUTOGIVE ID
SUBJECT WANTS TO TAKE
NAME
PASSWORD
**ONCE INSIDE QUIZ STUDENT WILL HAVE:
SUBJECT SCORE
=(optional) POINTS TO REDEEM FOR HINT

FOR TEACHERS :
LOGIN
SIGNUP
**TEACHER INFO
NAME
SUBJECT WNATS TO CONTRIBUTE
AUTOGIVE ID
**FOR EDITING 
ADD SUBJECT
ADD QUESTIONS
"BY : TEACHERSNAME"
CANT EDIT OTHER'S CONTRIBUTION

STUDENTS MENU:
(1) LOGIN, SIGNUP
(2) CHOOSE SUBJECT, EDIT SUBJECT, VIEW SCORE AND POINTS, BACK
(3)**ONCE INSIDE SUBJECT, START QUIZ, BACK

TEACHER'S MENU
(1) LOGIN, SIGNUP
(2) CHOOSE SUBJECT TO EDIT, VIEW QUESTIONS AND ANSWERS, BACK
(3)**ONCE INSIDE SUBJECT, EDIT QUESTION (ADD, DELETE)


ADMIN MENU 
(1) LOGIN
(2) VIEW PARTICIPANT LIST (STUDENT AND TEACHER), BACK



*/ 